# Generated by Django 4.1.3 on 2023-02-01 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locality', models.FloatField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('mobile', models.IntegerField()),
                ('state', models.CharField(choices=[('TOGO', 'Lomé'), ('GHANA', 'ACCRA'), ('BENIN', 'ytgh'), ('MALI', 'BAMAKO'), ('FRANCE', 'PARIS'), ('BELGIQUE', 'BRUXELLE'), ('HAITI', 'PORT-AU-PRINCE')], max_length=100)),
                ('zipcode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
